### ISSUE TITLE
Не компилируется

### ISSUE THREAD

**Issue by msink** [monakhv/samlib-Info#3]
Android Studio ругается:

    E:\android\workspace\samlib-Info\samlib-core\src\monakhv\samlib\db\entity\SamLibConfig.java
    Error:(53, 146) error: unmappable character for encoding Cp1251
    Error:(80, 65) error: unmappable character for encoding Cp1251

Зачем ей 1251 понадобился?
Везде где можно вроде UTF8 выбран...

**Comment by monakhv** [comment]
По умолчанию при компиляции на винде, полрузумевается, что исходник
кодирован в Cp1251. Попробуйте в опциях компилятора указать -encoding UTF-8

2015-05-26 13:59 GMT+03:00 Mike Sinkovsky <notifications@github.com>:

**Comment by msink** [comment]
Да, если добавить в samlib-core/build.gradle

    compileJava.options.encoding = 'UTF-8'

то компилируется и запускается.

Только еще два ворнинга в логе:

    Warning:Dependency org.apache.httpcomponents:httpclient:4.2.3 is ignored for debug as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
    Warning:Dependency org.apache.httpcomponents:httpclient:4.2.3 is ignored for release as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages

Это нормально или тоже надо как-то фиксить?

**Comment by monakhv** [comment]
Можно игнорировать. Дело в том, что для будущей десктопной версии, эта библиотека действительно нужна, но а в Android она действительно есть по умолчанию в стандартной конфигурации.

**Comment by msink** [comment]
Ну ладно.
Но строчку с кодировкой может добавите, если она на винде нужна, а на лин/мак не мешает?
Чтоб другие потом на эти грабли не наступали.

**Comment by monakhv** [comment]
ОК! Это будет. 
Хотя по хорошему бы надо все это в в ресурсы задвинуть, чтобы было не завмисимо от платформы, но с опцией это сделать действительно проще.
